version: "3.8"
services:
    web:
        build: .
        ports:
            - "5000:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: ".=xg2]V5"
            ACCEPT_EULA: "Y"
